AWSTemplateFormatVersion: '2010-09-09'
Description: Secure Serverless File Upload with Automatic PDF Extraction

Parameters:
  GitHubRepo:
    Type: String
    Description: 'GitHub repo in format "owner/repo"'

  GitHubAccessToken:
    Type: String
    NoEcho: true
    Description: 'GitHub token with repo + admin:repo_hook'

  UploadPassword:
    Type: String
    NoEcho: true
    Description: 'Password for uploads'

  S3BucketName:
    Type: String
    Description: 'Bucket name for file storage'

  LambdaCodeBucket:
    Type: String
    Description: 'S3 bucket containing lambda zip file'

  LambdaCodeKey:
    Type: String
    Description: 'S3 key for lambda zip file'

  CompanyName:
    Type: String
    Default: "AI Guru"
    Description: 'Displayed in UI'

  LogoUrl:
    Type: String
    Description: 'URL to company logo image'
    Default: "https://via.placeholder.com/150x50/0066cc/ffffff?text=Logo"

  CustomDomainName:
    Type: String
    Description: 'Custom domain name (e.g., yourdomain.com)'

  CustomDomainPrefix:
    Type: String
    Default: "fileupload"
    Description: 'Subdomain prefix (e.g., fileupload)'

Resources:
  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .pdf
            Function: !GetAtt LambdaFunction.Arn

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*

  # Lambda Function (handles presigned URL generation + PDF extraction)
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${CustomDomainPrefix}Lambda"
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Environment:
        Variables:
          UPLOAD_PASSWORD: !Ref UploadPassword
          UPLOAD_BUCKET: !Ref S3BucketName
          REGION: !Ref AWS::Region
      Timeout: 300
      MemorySize: 512

  # Lambda Permission for S3 trigger
  LambdaPermissionForS3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::${S3BucketName}

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: FileUploadAPI
      EndpointConfiguration:
        Types: [REGIONAL]

  # /generate-bulk-upload-urls Resource
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: generate-bulk-upload-urls

  # POST /generate-bulk-upload-urls
  ApiMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: LambdaFunction
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # OPTIONS /generate-bulk-upload-urls (CORS)
  ApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
            ResponseTemplates:
              application/json: '{}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  # Lambda permission for API Gateway
  LambdaPermissionForApi:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/generate-bulk-upload-urls

  # API Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiMethod
      - ApiOptionsMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  # Amplify Role
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify

  # Amplify App
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: FileUploadApp
      Repository: !Ref GitHubRepo
      AccessToken: !Ref GitHubAccessToken
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      BuildSpec: !Sub |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - sed -i "s|%%API_URL%%|${ApiUrl}|g" index.html
                - sed -i "s|%%COMPANY_NAME%%|${CompanyName}|g" index.html
                - sed -i "s|%%LOGO_URL%%|${LogoUrl}|g" index.html
            build:
              commands:
                - echo "Static site - no build step needed"
          artifacts:
            baseDirectory: .
            files:
              - '**/*'
      EnvironmentVariables:
        - Name: ApiUrl
          Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/generate-bulk-upload-urls'
        - Name: CompanyName
          Value: !Ref CompanyName
        - Name: LogoUrl
          Value: !Ref LogoUrl

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    DependsOn: AmplifyApp
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true

Outputs:
  AppUrl:
    Description: Amplify App URL
    Value: !GetAtt AmplifyApp.DefaultDomain
  
  CustomDomainUrl:
    Description: Custom Domain URL (requires DNS configuration)
    Value: !Sub 'https://${CustomDomainPrefix}.${CustomDomainName}'
  
  ApiEndpoint:
    Description: API Gateway Endpoint
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/generate-bulk-upload-urls'
  
  S3Bucket:
    Description: S3 Bucket Name
    Value: !Ref S3BucketName
